name: Deploy Site on push
on:
  push:
    branches:
      - develop
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy: 
        matrix:
            node-version: [16.x]
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} to Install project dependencies
      uses: actions/setup-node@master
      with:
          node-version: ${{ matrix.node-version }}
    - name: Installing project dependencies
      run: npm install
    - name: Building the project
      env:
            REACT_APP_PAYSTACK_PUBLIC_KEY: ${{secrets.REACT_APP_PAYSTACK_PUBLIC_KEY}}
            REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}
      run: npm run build
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.3
      with:
        server: ftp.reginapaciscc.org
        username: ${{secrets.NODE_SITE_USER}}
        password: ${{secrets.NODE_SITE_PASS}}
        server-dir: /
#         exclude: |
#           **/.git*
#           **/.git*/**
#           **/node_modules/**
#           **/.**/**
